version: '3.3'
volumes:
  pg_data_production:
  static_volume:
  media_volume:
  redoc:
services:
  db:
    container_name: postgres_db
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
      - ./data/ingredients.csv:/var/lib/postgresql/data/ingredients.csv
  backend:
    container_name: foodgram_backend
    image: s0rath/foodgram_backend
    environment:
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=django
      - DB_HOST=db
      - DB_PORT=5432
      - SECRET_KEY='django-insecure-04dakutiig6wulbmmodkx_oh(+)jkh&rc06hprp@g%$$^=yi3('
    network_mode: host
    restart: always
    depends_on:
      - db
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
      - redoc:/app/api/docs/
  frontend:
    container_name: foodgram_frontend
    image: s0rath/foodgram_frontend
    env_file: .env
    volumes:
      - static_volume:/frontend_static
      - media_volume:/app/media/     
  nginx:
    container_name: nginx
    image: s0rath/foodgram_gateway
    restart: always
    env_file: .env
    ports:
      - 9000:80
    depends_on:
     - backend
     - frontend
    volumes:
      - static_volume:/static
      - media_volume:/app/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/ 
