version: '3.3'
volumes:
  pg_data_production:
  static_volume:
  media_volume:
  redoc:
services:
  
  db:
    image: postgres:13.4-alpine 
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
      - ./data/ingredients.csv:/var/lib/postgresql/data/ingredients.csv
    expose:
      - '5432'  
   
  backend:
    image: s0rath/foodgram_backend
    env_file: .env
    restart: always
    depends_on:
      - db
    volumes:
      - static_volume:/backend_static
      - media_volume:/app/media/
      - redoc:/app/api/docs/
    links:
      - db  
   
  frontend:
    image: s0rath/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - ./frontend/:/app/
      - static_volume:/frontend_static/
      - media_volume:/app/media/
  
  nginx:
    image: s0rath/foodgram_gateway
    restart: always 
    env_file: .env
    ports:
     - 9000:80
    depends_on:
     - backend
    volumes:
      - static_volume:/staticfiles/
      - media_volume:/media/ 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
