version: '3.3'
volumes:
  pg_data:
  static:
  media:
services:
  db:
    container_name: postgres_db
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./data/ingredients.csv:/var/lib/postgresql/data/ingredients.csv
  backend:
    container_name: backend
    build: ./backend/
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/app/static/
      - media:/app/media/
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: cp -r /app/build/static/. /app/static/
    volumes:
      - static:/app/static/
  nginx:
    container_name: nginx
    image: nginx:1.22.1
    ports:
      - 9000:80
    depends_on:
     - backend
     - frontend
    volumes:
      - static:/app/static/
      - media:/app/media/
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
