version: '3.3'
volumes:
  pg_data_production:
  static_volume:
  media_volume:
  redoc:
services:
  db:
    
    image: postgres:13.10
    # environment:
    #   PGDATA: /var/lib/postgresql/data
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
      #- ./data/ingredients.csv:/var/lib/postgresql/data/ingredients.csv
  backend:
    
    image: s0rath/foodgram_backend
    env_file: .env
    restart: always
    depends_on:
      - db
    volumes:
      - static_volume:/backend_static
      - media_volume:/app/media/
      - redoc:/app/api/docs/
  frontend:
    
    image: s0rath/foodgram_frontend
    env_file: .env
    volumes:
      - static_volume:/frontend_static
      - media_volume:/app/media/     
  nginx:
    
    image: s0rath/foodgram_gateway
    restart: always
    env_file: .env
    ports:
      - 9000:80
    depends_on:
     - backend
    volumes:
      - static_volume:/staticfiles/
      - media_volume:/app/media/ 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
